project_name: gym
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: zbindenren
    name: gym
  # name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - linux
  binary: gym
  goarch:
    - amd64
  main: ./cmd/gym.go
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}-{{ .Version }}"
  replacements:
    amd64: x86_64
nfpm:
  formats:
    - rpm
  vendor: "Rene Zbinden"
  homepage: "https://github.com/zbindenren/gym"
  maintainer: "Rene Zbinden <rene.zbinden@postfinance.ch>"
  description: "Golang YUM Mirror"
  license: "Apache 2.0"
  bindir: /usr/bin
  name_template: "{{.ProjectName}}-{{.Version}}.el7.{{.Arch}}"
  replacements:
    amd64: x86_64
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
