deps:
  cmds:
    - glide install
  generates:
    - vendor/
  sources:
    - glide.yaml
    - glide.lock

build-fast:
  desc: run this task to make compiling fast again
  deps: [deps]
  cmds:
    - cd cmd; go build -i -v

build: &build
  deps:
    - deps
  desc: build gym binary
  sources:
    - cmd/main.go
    - './*.go'
  generates:
    - dist/gym
  cmds:
    - go build -ldflags "-s -w" -o dist/gym cmd/gym.go

install:
  deps:
    - build
  sources:
    - dist/gym
  generates:
    - "{{.PACKAGE_INSTALL_PREFIX}}/usr/bin/gym"
  cmds:
    - install -D -m 755 dist/gym {{.PACKAGE_INSTALL_PREFIX}}/usr/bin/gym

rpm:
   deps:
     - install
   sources:
     - "{{.PACKAGE_INSTALL_PREFIX}}/usr/bin/gym"
   generates:
     - task-{{.PACKAGE_VERSION}}*.rpm
   cmds:
     - |
       fpm -s dir -t rpm -v {{.PACKAGE_VERSION}} \
       -n {{.NAME}} \
       --url {{.URL}} \
       --category {{.PACKAGE_GROUP}} \
       --iteration {{.GIT_REVCOUNT}}.el{{.OS_VERSION}} \
       --description "{{.PACKAGE_SUMMARY}}" \
       -C {{.PACKAGE_INSTALL_PREFIX}}

clean:
  cmds:
    - rm -f *.rpm
    - rm -rf root
    - rm -rf vendor
    - rm -rf dist
